from pydantic import BaseModel
from enum import Enum

class LanguageCode(str, Enum):
    english="en"
    arabic="ar"
    bengali="bn"
    bulgarian="bg"
    chinese_simplified="zh"
    chinese_traditional="zh_tw"
    czech="cs"
    danish="da"
    dutch="nl"
    finnish="fi"
    french="fr"
    german="de"
    greek="el"
    hindi="hi"
    hungarian="hu"
    italian="it"
    japanese="ja"
    javanese="jv"
    korean="ko"
    mandarin="zh_cmn"
    marathi="mr"
    polish="pl"
    portugese="pt"
    punjabi="pa"
    romanian="ro"
    russian="ru"
    serbian="sr"
    sinhalese="si"
    slovak="sk"
    spanish="es"
    swedish="sv"
    tamil="ta"
    telugu="te"
    turkish="tr"
    ukrainian="uk"
    urdu="ur"
    vietnamese="vi"

